config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: 'welcome#index'
  get '/about', to: 'welcome#about'

  resources :companies

end

app/models/company.rb
class Company < ActiveRecord::Base

  mount_uploader :logo, LogoUploader

  validates :name, presence: true
  validates :latitude, numericality: {greater_than_or_equal_to: -90, less_than_or_equal_to: 90}, allow_nil: true
  validates :longitude, numericality: {greater_than_or_equal_to: -180, less_than_or_equal_to: 180}, allow_nil: true

  def self.coordinates
    where.not(latitude: nil, longitude: nil).map do |company|
      {
        latitude: company.latitude,
        longitude: company.longitude
      }
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include AuthenticationConcern

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all.page(params[:page]).per(8)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :logo, :logo_cache, :address, :latitude, :longitude, :description)
    end
end

app/controllers/concerns/authentication_concern.rb
module AuthenticationConcern
  extend ActiveSupport::Concern

  included do
    before_action :authenticate_user!
  end

  protected

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  skip_before_action :authenticate_user!, only: [:about]

  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def modal_button(text, target)
    content_tag(:button, text, type: 'button', class: 'btn btn-default btn-xs',
                data: {target: target, toggle: 'modal'})
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/_company.html.haml
.company
  %p
    = link_to company.name, company_path(company)
  = image_tag company.logo_url, width: 190, height: 190

app/views/companies/_company.html.slim
.company
  p
    = link_to company.name, company_path(company)
  = image_tag company.logo_url, width: 190, height: 190

app/views/companies/_coords_json.html.slim
meta name="company_coords" content=Company.coordinates.to_json

app/views/companies/_form.html.haml
.panel.panel-default
  .panel-body
    = simple_form_for(@company, html: {class: 'form-horizontal'}, wrapper: :horizontal_form) do |f|
      = f.error_notification

      = f.input :name
      = f.input :logo, wrapper: :horizontal_file_input, as: :image_preview
      = f.hidden_field :logo_cache
      = f.input :address
      = f.input :latitude
      = f.input :longitude, hint: modal_button("select the company's coordinates", '#rsm-coords-selector')
      = f.input :description

      = f.button :submit


- content_for :modal do
  .modal.fade#rsm-coords-selector{tabindex: '-1'}
    .modal-dialog.modal-lg
      .modal-content
        .modal-header
          %button.close{type: 'button', data: {dismiss: 'modal'}}
            %span &times;
          %h4 Select LatLng

        .modal-body
          %p#rsm-latlng LatLng:
          #rsm-coords-map

        .modal-footer
          %button.btn.btn-default{type: 'button', data: {dismiss: 'modal'}} Close
          %button.btn.btn-primary#rsm-coords-save-button{type: 'button', data: {dismiss: 'modal'}} Save Changes

app/views/companies/_form.html.slim
.panel.panel-default
  .panel-body
    = simple_form_for(@company, html: {class: 'form-horizontal'}, wrapper: :horizontal_form) do |f|
      = f.error_notification

      = f.input :name
      = f.input :logo, wrapper: :horizontal_file_input, as: :image_preview
      = f.hidden_field :logo_cache
      = f.input :address
      = f.input :latitude
      = f.input :longitude, hint: modal_button("select the company's coordinates", '#rsm-coords-selector')
      = f.input :description

      = f.button :submit


- content_for :modal do
  .modal.fade#rsm-coords-selector tabindex="-1"
    .modal-dialog.modal-lg
      .modal-content
        .modal-header
          button.close type="button" data={dismiss: 'modal'}
            span &times;
          h4 Select LatLng

        .modal-body
          p#rsm-latlng LatLng:
          #rsm-coords-map

        .modal-footer
          button.btn.btn-default type="button" data={dismiss: 'modal'} Close
          button.btn.btn-primary#rsm-coords-save-button type="button" data={dismiss: 'modal'} Save Changes

app/views/companies/edit.html.haml
%h1 Editing company

= render 'form'

= link_to 'Show', @company
\|
= link_to 'Back', companies_path

app/views/companies/edit.html.slim
h1 Editing company

= render 'form'

= link_to 'Show', @company
| |
= link_to 'Back', companies_path

app/views/companies/index.html.slim
h1 Listing companies

#companies
  = render @companies

nav
  = paginate @companies

/= link_to 'New Company', new_company_path

app/views/companies/new.html.haml
%h1 New company

= render 'form'

= link_to 'Back', companies_path

app/views/companies/new.html.slim
h1 New company

= render 'form'

= link_to 'Back', companies_path

app/views/companies/show.html.haml
%p#notice= notice

%p
  = @company.name

%p
  = image_tag(@company.logo_url)

= link_to 'Edit', edit_company_path(@company)
\|
= link_to 'Back', companies_path

app/views/companies/show.html.slim
p#notice= notice

p
  = @company.name

p
  = image_tag(@company.logo_url)

= link_to 'Edit', edit_company_path(@company)
| |
= link_to 'Back', companies_path

app/views/layouts/_footer.html.slim
footer
  .container
    | RedStoneMap is powered by Rails.

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{type: 'button', data: {toggle: 'collapse', target: '#rsm-navbar-collapse'}}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'RedStoneMap', root_path, class: 'navbar-brand'

    .navbar-collapse.collapse#rsm-navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to 'Companies', companies_path
        %li
          = link_to 'About', about_path
        - if user_signed_in?
          %li.dropdown
            = link_to '#', class: 'dropdown-toggle', 'data-toggle' => "dropdown" do
              = current_user.email
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to('Sign out', destroy_user_session_path, method: :delete)
        - else
          %li
            = link_to 'Sign in', new_user_session_path

app/views/layouts/_header.html.slim
nav.navbar.navbar-default
  .container
    .navbar-header
      button.navbar-toggle.collapsed type="button" data={toggle: 'collapse', target: '#rsm-navbar-collapse'}
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'RedStoneMap', root_path, class: 'navbar-brand'

    .navbar-collapse.collapse#rsm-navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li
          = link_to 'Companies', companies_path
        li
          = link_to 'About', about_path
        - if user_signed_in?
          li.dropdown
            = link_to '#', class: 'dropdown-toggle', 'data-toggle' => "dropdown" do
              = current_user.email
              span.caret
            ul.dropdown-menu
              li
                = link_to('Sign out', destroy_user_session_path, method: :delete)
        - else
          li
            = link_to 'Sign in', new_user_session_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Redstonemap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'http://api.map.baidu.com/api?v=1.5&ak=sXqGyUaOEt3Q3XHIu68XDgXK' %>
  <%= csrf_meta_tags %>
  <%= render 'companies/coords_json' %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="main container">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

  <%= content_for :modal %>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/about.html.slim
h1 Welcome#about

app/views/welcome/index.html.haml
.panel.panel-default
  .panel-body
    index page

#map-container

app/views/welcome/index.html.slim
.panel.panel-default
  .panel-body
    | index page

#map-container.map-container